# version: '2'
# services:
#   nginx:
#     image: nginx
#     container_name: nginx
#     ports:
#       - "80:80"
#     volumes:
#       - /etc/nginx/conf.d

#   dockergen:
#     image: jwilder/docker-gen
#     command: -notify-sighup nginx -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
#     volumes_from:
#       - nginx
#     volumes:
#       - /var/run/docker.sock:/tmp/docker.sock:ro
#       - /opt/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl

#   whoami:
#     image: jwilder/whoami
#     environment:
#       - VIRTUAL_HOST=whoami.local



version: '2'
services:
  hubot:
    environment:
      - LETSENCRYPT_HOST=ci.hrquest.io
      - LETSENCRYPT_EMAIL=kremenets0207@gmail.com
      - VIRTUAL_HOST=ci.hrquest.io
      - VIRTUAL_PORT=8443
      - VIRTUAL_PORT_API=8080
      - TELEGRAM_WEBHOOK=https://ci.hrquest.io

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt
    volumes_from:
      - nginx
    volumes:
      - ./ssl:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/nginx/conf.d
      - /etc/nginx/vhost.d
      - ./ssl:/etc/nginx/certs:ro
      - /usr/share/nginx/html

  dockergen:
    image: jwilder/docker-gen
    command: -notify-sighup nginx -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    volumes_from:
      - nginx
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /opt/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl

  # nginx-proxy:
  #   image: jwilder/nginx-proxy
  #   container_name: nginx-proxy
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - /var/run/docker.sock:/tmp/docker.sock:ro
  #     - ./ssl:/etc/nginx/certs:ro
  #     - /etc/nginx/vhost.d
  #     # - ./nginx.tmpl:/app/nginx.tmpl
  #     - /usr/share/nginx/html
