version: '2'
services:
  hubot:
    image: makeomatic/hubot-ci
    container_name: hubot
    hostname: hubot
    command: bin/hubot -a adapter-telegram
    environment:
      - TELEGRAM_TOKEN=271719585:AAE87oZtTcgFd-ByufWzeZvjyKqzPQmpPqQ
      - HUBOT_NAME=FaceToHealthBuildBot
      - HUBOT_LOG_LEVEL=debug
      - EXPRESS_PORT=8080
    expose:
      - "8443"
      - "8080"

